// packages/react-router/src/scroll-restoration.tsx
import { getScrollRestorationScriptForRouter } from '@benjavicente/router-core/scroll-restoration-script'
import { useRouter } from './useRouter'
import { ScriptOnce } from './ScriptOnce'

export function ScrollRestoration() {
  const router = useRouter()
  const script = getScrollRestorationScriptForRouter(router)

  if (!script) {
    return null
  }

  return <ScriptOnce children={script} />
}

// packages/vue-router/src/scroll-restoration.tsx
import * as Vue from 'vue'
import { getScrollRestorationScriptForRouter } from '@benjavicente/router-core/scroll-restoration-script'
import { useRouter } from './useRouter'
import { ScriptOnce } from './ScriptOnce'

export const ScrollRestoration = Vue.defineComponent({
  name: 'ScrollRestoration',
  setup() {
    const router = useRouter()

    return () => {
      const script = getScrollRestorationScriptForRouter(router)

      if (script) {
        return <ScriptOnce children={script} />
      }

      return null
    }
  },
})
