// packages/solid-router/src/useRouter.tsx
import * as Solid from 'solid-js'
import { routerContext } from './routerContext'
import type { AnyRouter, RegisteredRouter } from '@benjavicente/router-core'

export function useRouter<TRouter extends AnyRouter = RegisteredRouter>(opts?: {
  warn?: boolean
}): TRouter {
  const value = Solid.useContext(routerContext as any)
  if (process.env.NODE_ENV !== 'production') {
    if ((opts?.warn ?? true) && !value) {
      console.warn(
        'Warning: useRouter must be used inside a <RouterProvider> component!',
      )
    }
  }
  return value as any
}

// packages/vue-router/src/useRouter.tsx
import * as Vue from 'vue'
import { routerContext } from './routerContext'
import type { AnyRouter, RegisteredRouter } from '@benjavicente/router-core'

export function useRouter<TRouter extends AnyRouter = RegisteredRouter>(opts?: {
  warn?: boolean
}): TRouter {
  const value = Vue.inject(routerContext as any, null)
  if (process.env.NODE_ENV !== 'production') {
    if ((opts?.warn ?? true) && !value) {
      console.warn(
        'Warning: useRouter must be used inside a <RouterProvider> component!',
      )
    }
  }
  return value as any
}
