// packages/angular-router-devtools/src/tanstack-router-devtools-panel.ts
import {
  Component,
  DestroyRef,
  ElementRef,
  EnvironmentInjector,
  afterNextRender,
  computed,
  effect,
  inject,
  input,
  runInInjectionContext,
} from '@angular/core'
import {
  injectRouter,
  injectStore,
} from '@benjavicente/angular-router-experimental'
import { TanStackRouterDevtoolsPanelCore } from '@benjavicente/router-devtools-core'
import type { AnyRouter } from '@benjavicente/angular-router-experimental'

export interface TanStackRouterDevtoolsPanelOptions {
  /**
   * The standard React style object used to style a component with inline styles
   */
  style?: Record<string, any>
  /**
   * The standard React class property used to style a component with classes
   */
  className?: string
  /**
   * A boolean variable indicating whether the panel is open or closed
   */
  isOpen?: boolean
  /**
   * A function that toggles the open and close state of the panel
   */
  setIsOpen?: (isOpen: boolean) => void
  /**
   * Handles the opening and closing the devtools panel
   */
  handleDragStart?: (e: any) => void
  /**
   * The router instance to use for the devtools, infered in the injector context if no provided.
   */
  router?: AnyRouter
  /**
   * Use this to attach the devtool's styles to specific element in the DOM.
   */
  shadowDOMTarget?: ShadowRoot
}

@Component({
  selector: 'tanstack-router-devtools-panel',
  template: '',
  styles: `
    :host {
      display: block;
    }
  `,
})
export class TanStackRouterDevtoolsPanel {
  style = input<TanStackRouterDevtoolsPanelOptions['style']>()
  className = input<TanStackRouterDevtoolsPanelOptions['className']>()
  isOpen = input<TanStackRouterDevtoolsPanelOptions['isOpen']>()
  setIsOpen = input<TanStackRouterDevtoolsPanelOptions['setIsOpen']>()
  handleDragStart =
    input<TanStackRouterDevtoolsPanelOptions['handleDragStart']>()
  inputRouter = input<TanStackRouterDevtoolsPanelOptions['router']>(undefined, {
    alias: 'router',
  })
  shadowDOMTarget =
    input<TanStackRouterDevtoolsPanelOptions['shadowDOMTarget']>()

  private elementRef = inject(ElementRef<HTMLElement>)

  private contextRouter = injectRouter({ warn: false })
  private router = computed(() => this.inputRouter() ?? this.contextRouter)
  private routerState = injectStore(() => this.router().stores.__store)

  private injector = inject(EnvironmentInjector)

  ngOnInit() {
    // Since inputs are not available before component initialization,
    // we attach every effect and derived signal to the ngOnInit lifecycle hook
    runInInjectionContext(this.injector, () => {
      const devtoolsPanel = new TanStackRouterDevtoolsPanelCore({
        style: this.style(),
        className: this.className(),
        isOpen: this.isOpen(),
        setIsOpen: this.setIsOpen(),
        handleDragStart: this.handleDragStart(),
        router: this.router(),
        routerState: this.routerState(),
      })

      effect(() => {
        devtoolsPanel.setRouter(this.router())
      })

      effect(() => {
        devtoolsPanel.setRouterState(this.routerState())
      })

      effect(() => {
        devtoolsPanel.setOptions({
          style: this.style(),
          className: this.className(),
          isOpen: this.isOpen(),
          setIsOpen: this.setIsOpen(),
          handleDragStart: this.handleDragStart(),
        })
      })

      const destroyRef = inject(DestroyRef)
      afterNextRender(() => {
        devtoolsPanel.mount(this.elementRef.nativeElement)
        destroyRef.onDestroy(() => {
          devtoolsPanel.unmount()
        })
      })
    })
  }
}

// packages/vue-router-devtools/src/TanStackRouterDevtoolsPanel.tsx
import { TanStackRouterDevtoolsPanelCore } from '@benjavicente/router-devtools-core'
import { defineComponent, h, onMounted, onUnmounted, ref, watch } from 'vue'
import { useRouter, useRouterState } from '@benjavicente/vue-router'
import type { AnyRouter } from '@benjavicente/vue-router'

export interface TanStackRouterDevtoolsPanelOptions {
  /**
   * The standard style object used to style a component with inline styles
   */
  style?: any
  /**
   * The standard class property used to style a component with classes
   */
  className?: string
  /**
   * A boolean variable indicating whether the panel is open or closed
   */
  isOpen?: boolean
  /**
   * A function that toggles the open and close state of the panel
   */
  setIsOpen?: (isOpen: boolean) => void
  /**
   * Handles the opening and closing the devtools panel
   */
  handleDragStart?: (e: any) => void
  /**
   * The router instance to use for the devtools.
   */
  router?: AnyRouter
  /**
   * Use this to attach the devtool's styles to specific element in the DOM.
   */
  shadowDOMTarget?: ShadowRoot
}

export const TanStackRouterDevtoolsPanel = /* #__PURE__ */ defineComponent({
  name: 'TanStackRouterDevtoolsPanel',
  props: [
    'style',
    'className',
    'isOpen',
    'setIsOpen',
    'handleDragStart',
    'router',
    'shadowDOMTarget',
  ] as unknown as undefined,
  setup(props: TanStackRouterDevtoolsPanelOptions) {
    const devToolRef = ref<HTMLDivElement | null>(null)
    let isMounted = false

    const hookRouter = useRouter({ warn: false })
    const activeRouter = props.router ?? hookRouter

    const activeRouterState = useRouterState({ router: activeRouter })

    const devtools = new TanStackRouterDevtoolsPanelCore({
      style: props.style,
      className: props.className,
      isOpen: props.isOpen,
      setIsOpen: props.setIsOpen,
      handleDragStart: props.handleDragStart,
      shadowDOMTarget: props.shadowDOMTarget,
      router: activeRouter,
      routerState: activeRouterState.value,
    })

    // Update devtools when router changes
    watch(
      () => activeRouter,
      (router) => {
        devtools.setRouter(router)
      },
    )

    // Update devtools when router state changes
    watch(activeRouterState, (routerState) => {
      devtools.setRouterState(routerState)
    })

    // Update devtools when options change
    watch(
      () => [props.className, props.style, props.shadowDOMTarget],
      () => {
        devtools.setOptions({
          className: props.className,
          style: props.style,
          shadowDOMTarget: props.shadowDOMTarget,
        })
      },
    )

    onMounted(() => {
      if (devToolRef.value) {
        devtools.mount(devToolRef.value)
        isMounted = true
      }
    })

    onUnmounted(() => {
      if (isMounted) {
        devtools.unmount()
      }
    })

    return () => h('div', { ref: devToolRef })
  },
})
