// examples/react/basic-ssr-streaming-file-based/src/routes/index.tsx
import { Await, createFileRoute } from '@benjavicente/react-router'
import * as React from 'react'

export const Route = createFileRoute('/')({
  loader: () => ({
    date: new Date(),
    deferred: new Promise<{ date: Date }>((r) =>
      setTimeout(() => r({ date: new Date() }), 1000),
    ),
  }),
  component: IndexComponent,
})

function IndexComponent() {
  const data = Route.useLoaderData()

  return (
    <div className="p-2">
      <h3>Welcome Home!</h3>
      <p>Data: {data.date.getDate()}</p>
      <Await promise={data.deferred} fallback="Loading...">
        {(data) => <p>Deferred: {new Date(data.date).getDate()}</p>}
      </Await>
    </div>
  )
}

// examples/angular/basic-file-based/src/routes/index.ts
import { Component } from '@angular/core'
import { createFileRoute } from '@benjavicente/angular-router-experimental'

export const Route = createFileRoute('/')({
  component: () => IndexComponent,
})

@Component({
  selector: 'route-component',
  standalone: true,
  template: `
    <div class="p-2">
      <h3>Welcome Home!</h3>
    </div>
  `,
})
class IndexComponent {}
