// examples/react/basic-react-query-file-based/src/routes/posts.route.tsx
import { createFileRoute } from '@benjavicente/react-router'
import * as React from 'react'
import { Link, Outlet } from '@benjavicente/react-router'
import { useSuspenseQuery } from '@tanstack/react-query'
import { postsQueryOptions } from '../postsQueryOptions'

export const Route = createFileRoute('/posts')({
  loader: ({ context: { queryClient } }) =>
    queryClient.ensureQueryData(postsQueryOptions),
  component: PostsLayoutComponent,
})

function PostsLayoutComponent() {
  const postsQuery = useSuspenseQuery(postsQueryOptions)
  const posts = postsQuery.data

  return (
    <div className="p-2 flex gap-2">
      <ul className="list-disc pl-4">
        {[...posts, { id: 'i-do-not-exist', title: 'Non-existent Post' }].map(
          (post) => {
            return (
              <li key={post.id} className="whitespace-nowrap">
                <Link
                  to="/posts/$postId"
                  params={{
                    postId: post.id,
                  }}
                  className="block py-1 text-blue-600 hover:opacity-75"
                  activeProps={{ className: 'font-bold underline' }}
                >
                  <div>{post.title.substring(0, 20)}</div>
                </Link>
              </li>
            )
          },
        )}
      </ul>
      <hr />
      <Outlet />
    </div>
  )
}

// examples/angular/basic-file-based/src/routes/posts.route.ts
import { Component, computed } from '@angular/core'
import {
  createFileRoute,
  Link,
  Outlet,
} from '@benjavicente/angular-router-experimental'
import { fetchPosts } from '../posts'

export const Route = createFileRoute('/posts')({
  loader: fetchPosts,
  component: () => PostsLayoutComponent,
})

@Component({
  selector: 'route-component',
  standalone: true,
  template: `
    <div class="p-2 flex gap-2">
      <ul class="list-disc pl-4">
        @for (post of postsWithFake(); track post.id) {
          <li class="whitespace-nowrap">
            <a
              [link]="{
                to: '/posts/$postId',
                params: { postId: post.id },
                activeProps: { class: 'font-bold underline' }
              }"
              class="block py-1 text-blue-600 hover:opacity-75"
            >
              <div>{{ post.title.substring(0, 20) }}</div>
            </a>
          </li>
        }
      </ul>
      <hr />
      <outlet />
    </div>
  `,
  imports: [Link, Outlet],
})
class PostsLayoutComponent {
  posts = Route.injectLoaderData()
  postsWithFake = computed(() => [
    ...this.posts(),
    { id: 'i-do-not-exist', title: 'Non-existent Post' },
  ])
}
