// examples/react/start-clerk-basic/src/routes/_authed/posts.$postId.tsx
import { ErrorComponent, createFileRoute } from '@benjavicente/react-router'
import type { ErrorComponentProps } from '@benjavicente/react-router'
import { NotFound } from '~/components/NotFound.js'
import { fetchPost } from '~/utils/posts.js'

export const Route = createFileRoute('/_authed/posts/$postId')({
  loader: ({ params: { postId } }) => fetchPost({ data: postId }),
  errorComponent: PostErrorComponent,
  component: PostComponent,
  notFoundComponent: () => {
    return <NotFound>Post not found</NotFound>
  },
})

export function PostErrorComponent({ error }: ErrorComponentProps) {
  return <ErrorComponent error={error} />
}

function PostComponent() {
  const post = Route.useLoaderData()

  return (
    <div className="space-y-2">
      <h4 className="text-xl font-bold underline">{post.title}</h4>
      <div className="text-sm">{post.body}</div>
    </div>
  )
}

// examples/angular/basic-file-based/src/routes/posts.$postId.ts
import { Component } from '@angular/core'
import {
  createFileRoute,
  injectErrorState,
} from '@benjavicente/angular-router-experimental'
import { fetchPost } from '../posts'

export const Route = createFileRoute('/posts/$postId')({
  loader: ({ params }) => fetchPost(params.postId),
  errorComponent: () => PostErrorComponent,
  notFoundComponent: () => PostNotFoundComponent,
  component: () => PostComponent,
})

@Component({
  selector: 'post-error',
  standalone: true,
  template: `
    <div>Error: {{ errorState().error.message }}</div>
    <button (click)="errorState().reset()">Reset</button>
  `,
})
class PostErrorComponent {
  errorState = injectErrorState()
}

@Component({
  selector: 'post-not-found',
  standalone: true,
  template: `<p>Post not found</p>`,
})
class PostNotFoundComponent {}

@Component({
  selector: 'route-component',
  standalone: true,
  template: `
    <div class="space-y-2">
      <h4 class="text-xl font-bold underline">{{ post().title }}</h4>
      <div class="text-sm">{{ post().body }}</div>
    </div>
  `,
})
class PostComponent {
  post = Route.injectLoaderData()
}
