// examples/react/basic-virtual-inside-file-based/src/routes/_layout/_layout-2.tsx
import { Link, Outlet, createFileRoute } from '@benjavicente/react-router'

export const Route = createFileRoute('/_layout/_layout-2')({
  component: LayoutComponent,
})

function LayoutComponent() {
  return (
    <div>
      <div>I'm a nested layout</div>
      <div className="flex gap-2 border-b">
        <Link
          to="/layout-a"
          activeProps={{
            className: 'font-bold',
          }}
        >
          Layout A
        </Link>
        <Link
          to="/layout-b"
          activeProps={{
            className: 'font-bold',
          }}
        >
          Layout B
        </Link>
      </div>
      <div>
        <Outlet />
      </div>
    </div>
  )
}

// examples/vue/basic-file-based-sfc/src/routes/_layout/_layout-2.component.vue
<script setup lang="ts">
import { Link, Outlet } from '@benjavicente/vue-router'
</script>

<template>
  <div>
    <div>I'm a nested layout</div>
    <div class="flex gap-2 border-b">
      <Link to="/layout-a" :activeProps="{ class: 'font-bold' }">
        Layout A
      </Link>
      <Link to="/layout-b" :activeProps="{ class: 'font-bold' }">
        Layout B
      </Link>
    </div>
    <div>
      <Outlet />
    </div>
  </div>
</template>
