// examples/react/start-basic/src/routes/lazy.route.lazy.tsx
import { createLazyFileRoute } from '@benjavicente/react-router'

export const Route = createLazyFileRoute('/lazy')({
  component: LazyRouteComponent,
})

function LazyRouteComponent() {
  return (
    <div className="p-2">
      <h3>Lazy Route</h3>
      <p>This route component is loaded from a separate lazy route chunk.</p>
    </div>
  )
}

// examples/angular/start-basic-react-query/src/routes/lazy.route.lazy.ts
import { Component } from '@angular/core'
import { createLazyFileRoute } from '@benjavicente/angular-router-experimental'

export const Route = createLazyFileRoute('/lazy')({
  component: () => LazyRouteComponent,
})

@Component({
  selector: 'lazy-route-component',
  standalone: true,
  template: `
    <div class="space-y-4">
      <h2 class="text-xl font-semibold">Lazy route loaded</h2>
      <p class="text-sm text-gray-700 dark:text-gray-300">
        This component is loaded from a <code>.lazy.ts</code> route module, so
        the Angular Start scaffold is at least able to host router-level lazy
        route imports today.
      </p>
    </div>
  `,
})
class LazyRouteComponent {}
