// packages/vue-router/src/not-found.tsx
import * as Vue from 'vue'
import { isNotFound } from '@benjavicente/router-core'
import { useStore } from '@tanstack/vue-store'
import { CatchBoundary } from './CatchBoundary'
import { useRouter } from './useRouter'
import type { ErrorComponentProps, NotFoundError } from '@benjavicente/router-core'

export function CatchNotFound(props: {
  fallback?: (error: NotFoundError) => Vue.VNode
  onCatch?: (error: Error) => void
  children: Vue.VNode
}) {
  const router = useRouter()
  // TODO: Some way for the user to programmatically reset the not-found boundary?
  const pathname = useStore(
    router.stores.location,
    (location) => location.pathname,
  )
  const status = useStore(router.stores.status, (value) => value)

  // Create a function that returns a VNode to match the SyncRouteComponent signature
  const errorComponentFn = (componentProps: ErrorComponentProps) => {
    const error = componentProps.error

    if (isNotFound(error)) {
      // If a fallback is provided, use it
      if (props.fallback) {
        return props.fallback(error)
      }
      // Otherwise return a default not found message
      return Vue.h('p', null, 'Not Found')
    } else {
      // Re-throw non-NotFound errors
      throw error
    }
  }

  return Vue.h(CatchBoundary, {
    getResetKey: () => `not-found-${pathname.value}-${status.value}`,
    onCatch: (error: Error) => {
      if (isNotFound(error)) {
        if (props.onCatch) {
          props.onCatch(error)
        }
      } else {
        throw error
      }
    },
    errorComponent: errorComponentFn,
    children: props.children,
  })
}

export const DefaultGlobalNotFound = Vue.defineComponent({
  name: 'DefaultGlobalNotFound',
  setup() {
    return () => Vue.h('p', null, 'Not Found')
  },
})

// packages/solid-router/src/not-found.tsx
import { isNotFound } from '@benjavicente/router-core'
import * as Solid from 'solid-js'
import { CatchBoundary } from './CatchBoundary'
import { useRouter } from './useRouter'
import type { NotFoundError } from '@benjavicente/router-core'

// Solid wraps non-Error throws in an Error and stores the original thrown value
// on `cause`, so component-thrown `notFound()` needs one extra unwrapping step.
export function getNotFound(
  error: unknown,
): (NotFoundError & { isNotFound: true }) | undefined {
  if (isNotFound(error)) {
    return error as NotFoundError & { isNotFound: true }
  }

  if (isNotFound((error as any)?.cause)) {
    return (error as any).cause as NotFoundError & { isNotFound: true }
  }

  return undefined
}

export function CatchNotFound(props: {
  fallback?: (error: NotFoundError) => Solid.JSX.Element
  onCatch?: (error: NotFoundError) => void
  children: Solid.JSX.Element
}) {
  const router = useRouter()
  // TODO: Some way for the user to programmatically reset the not-found boundary?
  const pathname = Solid.createMemo(() => router.stores.location.state.pathname)
  const status = Solid.createMemo(() => router.stores.status.state)

  return (
    <CatchBoundary
      getResetKey={() => `not-found-${pathname()}-${status()}`}
      onCatch={(error) => {
        const notFoundError = getNotFound(error)

        if (notFoundError) {
          props.onCatch?.(notFoundError)
        } else {
          throw error
        }
      }}
      errorComponent={({ error }) => {
        const notFoundError = getNotFound(error)

        if (notFoundError) {
          return props.fallback?.(notFoundError)
        } else {
          throw error
        }
      }}
    >
      {props.children}
    </CatchBoundary>
  )
}

export function DefaultGlobalNotFound() {
  return <p>Not Found</p>
}
