// packages/vue-router/src/ssr/renderRouterToStream.tsx
import { ReadableStream as NodeReadableStream } from 'node:stream/web'
import * as Vue from 'vue'
import { pipeToWebWritable, renderToString } from 'vue/server-renderer'
import { isbot } from 'isbot'
import { transformReadableStreamWithRouter } from '@benjavicente/router-core/ssr/server'
import type { AnyRouter } from '@benjavicente/router-core'
import type { Component } from 'vue'

function prependDoctype(
  readable: globalThis.ReadableStream,
): NodeReadableStream<Uint8Array> {
  const encoder = new TextEncoder()
  let sentDoctype = false

  return new NodeReadableStream<Uint8Array>({
    start(controller) {
      const reader = readable.getReader()

      async function pump(): Promise<void> {
        const { done, value } = await reader.read()
        if (done) {
          controller.close()
          return
        }

        if (!sentDoctype) {
          sentDoctype = true
          controller.enqueue(encoder.encode('<!DOCTYPE html>'))
        }
        controller.enqueue(value)
        return pump()
      }

      pump().catch((err) => controller.error(err))
    },
  })
}

export const renderRouterToStream = async ({
  request,
  router,
  responseHeaders,
  App,
}: {
  request: Request
  router: AnyRouter
  responseHeaders: Headers
  App: Component
}) => {
  const app = Vue.createSSRApp(App, { router })

  if (isbot(request.headers.get('User-Agent'))) {
    let fullHtml = await renderToString(app)

    const htmlOpenIndex = fullHtml.indexOf('<html')
    const htmlCloseIndex = fullHtml.indexOf('</html>')

    if (htmlOpenIndex !== -1 && htmlCloseIndex !== -1) {
      fullHtml = fullHtml.slice(htmlOpenIndex, htmlCloseIndex + 7)
    } else if (htmlOpenIndex !== -1) {
      fullHtml = fullHtml.slice(htmlOpenIndex)
    }

    return new Response(`<!DOCTYPE html>${fullHtml}`, {
      status: router.stores.statusCode.state,
      headers: responseHeaders,
    })
  }

  const { writable, readable } = new TransformStream()

  pipeToWebWritable(app, {}, writable)

  const doctypedStream = prependDoctype(readable)
  const responseStream = transformReadableStreamWithRouter(
    router,
    doctypedStream,
  )

  return new Response(responseStream as any, {
    status: router.stores.statusCode.state,
    headers: responseHeaders,
  })
}

// packages/solid-router/src/ssr/renderRouterToStream.tsx
import * as Solid from 'solid-js/web'
import { isbot } from 'isbot'
import { transformReadableStreamWithRouter } from '@benjavicente/router-core/ssr/server'
import { makeSsrSerovalPlugin } from '@benjavicente/router-core'
import type { JSXElement } from 'solid-js'
import type { ReadableStream } from 'node:stream/web'
import type { AnyRouter } from '@benjavicente/router-core'

export const renderRouterToStream = async ({
  request,
  router,
  responseHeaders,
  children,
}: {
  request: Request
  router: AnyRouter
  responseHeaders: Headers
  children: () => JSXElement
}) => {
  const { writable, readable } = new TransformStream()

  const docType = Solid.ssr('<!DOCTYPE html>')

  const serializationAdapters =
    (router.options as any)?.serializationAdapters ||
    (router.options.ssr as any)?.serializationAdapters
  const serovalPlugins = serializationAdapters?.map((adapter: any) => {
    const plugin = makeSsrSerovalPlugin(adapter, { didRun: false })
    return plugin
  })

  const stream = Solid.renderToStream(
    () => (
      <>
        {docType}
        {children()}
      </>
    ),
    {
      nonce: router.options.ssr?.nonce,
      plugins: serovalPlugins,
    } as any,
  )

  if (isbot(request.headers.get('User-Agent'))) {
    await stream
  }
  stream.pipeTo(writable)

  const responseStream = transformReadableStreamWithRouter(
    router,
    readable as unknown as ReadableStream,
  )
  return new Response(responseStream as any, {
    status: router.stores.statusCode.state,
    headers: responseHeaders,
  })
}
