// packages/vue-router/src/ssr/RouterServer.tsx
import * as Vue from 'vue'
import { Asset } from '../Asset'
import { useTags } from '../headContentUtils'
import { RouterProvider } from '../RouterProvider'
import { Scripts } from '../Scripts'
import type { AnyRouter, RouterManagedTag } from '@benjavicente/router-core'

const ServerHeadContent = Vue.defineComponent({
  name: 'ServerHeadContent',
  setup() {
    const getTags = useTags()

    return () =>
      getTags().map((tag: RouterManagedTag) =>
        Vue.h(Asset, { key: tag.tag + (tag as any).id, ...tag }),
      )
  },
})

export const RouterServer = Vue.defineComponent({
  name: 'RouterServer',
  props: {
    router: {
      type: Object as () => AnyRouter,
      required: true,
    },
  },
  setup(props) {
    return () =>
      Vue.h('html', null, [
        Vue.h('head', null, [Vue.h(ServerHeadContent)]),
        Vue.h('body', null, [
          Vue.h('div', { id: '__app' }, [
            Vue.h(
              RouterProvider,
              {
                router: props.router,
              },
              {
                innerWrap: (innerProps: { children: any }) => [
                  Vue.h(ServerHeadContent),
                  innerProps.children,
                  Vue.h(Scripts),
                ],
              },
            ),
          ]),
        ]),
      ])
  },
})

// packages/solid-router/src/ssr/RouterServer.tsx
import {
  Hydration,
  HydrationScript,
  NoHydration,
  ssr,
  useAssets,
} from 'solid-js/web'
import { MetaProvider } from '@solidjs/meta'
import { Asset } from '../Asset'
import { useTags } from '../headContentUtils'
import { RouterProvider } from '../RouterProvider'
import { Scripts } from '../Scripts'
import type { AnyRouter } from '@benjavicente/router-core'

export function ServerHeadContent() {
  const tags = useTags()
  useAssets(() => {
    return (
      <MetaProvider>
        {tags().map((tag) => (
          <Asset {...tag} />
        ))}
      </MetaProvider>
    )
  })
  return null
}

const docType = ssr('<!DOCTYPE html>')

export function RouterServer<TRouter extends AnyRouter>(props: {
  router: TRouter
}) {
  return (
    <NoHydration>
      {docType as any}
      <html>
        <head>
          <HydrationScript />
        </head>
        <body>
          <Hydration>
            <RouterProvider
              router={props.router}
              InnerWrap={(props) => (
                <NoHydration>
                  <MetaProvider>
                    <ServerHeadContent />
                    <Hydration>{props.children}</Hydration>
                    <Scripts />
                  </MetaProvider>
                </NoHydration>
              )}
            />
          </Hydration>
        </body>
      </html>
    </NoHydration>
  )
}
