// examples/solid/quickstart-esbuild-file-based/src/main.tsx
import { render } from 'solid-js/web'
import { RouterProvider, createRouter } from '@benjavicente/solid-router'
import { routeTree } from './routeTree.gen'
import './styles.css'

// Set up a Router instance
const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  scrollRestoration: true,
})

// Register things for typesafety
declare module '@benjavicente/solid-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('app')!

if (!rootElement.innerHTML) {
  render(() => <RouterProvider router={router} />, rootElement)
}

// benchmarks/bundle-size/scenarios/vue-router-minimal/src/main.tsx
import { createApp } from 'vue'
import { RouterProvider, createRouter } from '@benjavicente/vue-router'
import { routeTree } from './routeTree.gen'

const router = createRouter({ routeTree })

declare module '@benjavicente/vue-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('app')
if (!rootElement) {
  throw new Error('Root element `#app` not found')
}
if (!rootElement.innerHTML) {
  createApp({
    setup() {
      return () => <RouterProvider router={router} />
    },
  }).mount('#app')
}
