// packages/vue-router-devtools/src/TanStackRouterDevtoolsPanel.tsx
import { TanStackRouterDevtoolsPanelCore } from '@benjavicente/router-devtools-core'
import { defineComponent, h, onMounted, onUnmounted, ref, watch } from 'vue'
import { useRouter, useRouterState } from '@benjavicente/vue-router'
import type { AnyRouter } from '@benjavicente/vue-router'

export interface TanStackRouterDevtoolsPanelOptions {
  /**
   * The standard style object used to style a component with inline styles
   */
  style?: any
  /**
   * The standard class property used to style a component with classes
   */
  className?: string
  /**
   * A boolean variable indicating whether the panel is open or closed
   */
  isOpen?: boolean
  /**
   * A function that toggles the open and close state of the panel
   */
  setIsOpen?: (isOpen: boolean) => void
  /**
   * Handles the opening and closing the devtools panel
   */
  handleDragStart?: (e: any) => void
  /**
   * The router instance to use for the devtools.
   */
  router?: AnyRouter
  /**
   * Use this to attach the devtool's styles to specific element in the DOM.
   */
  shadowDOMTarget?: ShadowRoot
}

export const TanStackRouterDevtoolsPanel = /* #__PURE__ */ defineComponent({
  name: 'TanStackRouterDevtoolsPanel',
  props: [
    'style',
    'className',
    'isOpen',
    'setIsOpen',
    'handleDragStart',
    'router',
    'shadowDOMTarget',
  ] as unknown as undefined,
  setup(props: TanStackRouterDevtoolsPanelOptions) {
    const devToolRef = ref<HTMLDivElement | null>(null)
    let isMounted = false

    const hookRouter = useRouter({ warn: false })
    const activeRouter = props.router ?? hookRouter

    const activeRouterState = useRouterState({ router: activeRouter })

    const devtools = new TanStackRouterDevtoolsPanelCore({
      style: props.style,
      className: props.className,
      isOpen: props.isOpen,
      setIsOpen: props.setIsOpen,
      handleDragStart: props.handleDragStart,
      shadowDOMTarget: props.shadowDOMTarget,
      router: activeRouter,
      routerState: activeRouterState.value,
    })

    // Update devtools when router changes
    watch(
      () => activeRouter,
      (router) => {
        devtools.setRouter(router)
      },
    )

    // Update devtools when router state changes
    watch(activeRouterState, (routerState) => {
      devtools.setRouterState(routerState)
    })

    // Update devtools when options change
    watch(
      () => [props.className, props.style, props.shadowDOMTarget],
      () => {
        devtools.setOptions({
          className: props.className,
          style: props.style,
          shadowDOMTarget: props.shadowDOMTarget,
        })
      },
    )

    onMounted(() => {
      if (devToolRef.value) {
        devtools.mount(devToolRef.value)
        isMounted = true
      }
    })

    onUnmounted(() => {
      if (isMounted) {
        devtools.unmount()
      }
    })

    return () => h('div', { ref: devToolRef })
  },
})

// packages/react-router-devtools/src/TanStackRouterDevtoolsPanel.tsx
import { useRouter, useRouterState } from '@benjavicente/react-router'
import { TanStackRouterDevtoolsPanelCore } from '@benjavicente/router-devtools-core'
import React, { useEffect, useRef, useState } from 'react'
import type { AnyRouter } from '@benjavicente/react-router'

export interface TanStackRouterDevtoolsPanelOptions {
  /**
   * The standard React style object used to style a component with inline styles
   */
  style?: any
  /**
   * The standard React class property used to style a component with classes
   */
  className?: string
  /**
   * A boolean variable indicating whether the panel is open or closed
   */
  isOpen?: boolean
  /**
   * A function that toggles the open and close state of the panel
   */
  setIsOpen?: (isOpen: boolean) => void
  /**
   * Handles the opening and closing the devtools panel
   */
  handleDragStart?: (e: any) => void
  /**
   * A boolean variable indicating if the "lite" version of the library is being used
   */
  router?: AnyRouter
  /**
   * Use this to attach the devtool's styles to specific element in the DOM.
   */
  shadowDOMTarget?: ShadowRoot
}

export const TanStackRouterDevtoolsPanel: React.FC<
  TanStackRouterDevtoolsPanelOptions
> = (props): React.ReactElement | null => {
  const { router: propsRouter, ...rest } = props
  const hookRouter = useRouter({ warn: false })
  const activeRouter = propsRouter ?? hookRouter
  const activeRouterState = useRouterState({ router: activeRouter })

  const devToolRef = useRef<HTMLDivElement>(null)
  const [devtools] = useState(
    () =>
      new TanStackRouterDevtoolsPanelCore({
        ...rest,
        router: activeRouter,
        routerState: activeRouterState,
      }),
  )

  // Update devtools when props change
  useEffect(() => {
    devtools.setRouter(activeRouter)
  }, [devtools, activeRouter])

  useEffect(() => {
    devtools.setRouterState(activeRouterState)
  }, [devtools, activeRouterState])

  useEffect(() => {
    devtools.setOptions({
      className: props.className,
      style: props.style,
      shadowDOMTarget: props.shadowDOMTarget,
    })
  }, [devtools, props.className, props.style, props.shadowDOMTarget])

  useEffect(() => {
    if (devToolRef.current) {
      devtools.mount(devToolRef.current)
    }

    return () => {
      devtools.unmount()
    }
  }, [devtools])

  return (
    <>
      <div ref={devToolRef} />
    </>
  )
}
