// examples/react/basic-react-query-file-based/src/routes/posts.$postId.tsx
import { createFileRoute } from '@benjavicente/react-router'
import * as React from 'react'
import { ErrorComponent, useRouter } from '@benjavicente/react-router'
import {
  useQueryErrorResetBoundary,
  useSuspenseQuery,
} from '@tanstack/react-query'
import { PostNotFoundError } from '../posts'
import { postQueryOptions } from '../postQueryOptions'
import type { ErrorComponentProps } from '@benjavicente/react-router'

export const Route = createFileRoute('/posts/$postId')({
  loader: ({ context: { queryClient }, params: { postId } }) => {
    return queryClient.ensureQueryData(postQueryOptions(postId))
  },
  errorComponent: PostErrorComponent,
  component: PostComponent,
})

export function PostErrorComponent({ error }: ErrorComponentProps) {
  const router = useRouter()
  if (error instanceof PostNotFoundError) {
    return <div>{error.message}</div>
  }
  const queryErrorResetBoundary = useQueryErrorResetBoundary()

  React.useEffect(() => {
    queryErrorResetBoundary.reset()
  }, [queryErrorResetBoundary])

  return (
    <div>
      <button
        onClick={() => {
          router.invalidate()
        }}
      >
        retry
      </button>
      <ErrorComponent error={error} />
    </div>
  )
}

function PostComponent() {
  const postId = Route.useParams().postId
  const { data: post } = useSuspenseQuery(postQueryOptions(postId))

  return (
    <div className="space-y-2">
      <h4 className="text-xl font-bold underline">{post.title}</h4>
      <div className="text-sm">{post.body}</div>
    </div>
  )
}

// examples/solid/basic-solid-query-file-based/src/routes/posts.$postId.tsx
import { createFileRoute } from '@benjavicente/solid-router'
import { ErrorComponent, useRouter } from '@benjavicente/solid-router'
import { useQuery } from '@tanstack/solid-query'
import { createEffect, createMemo } from 'solid-js'
import { PostNotFoundError } from '../posts'
import { postQueryOptions } from '../postQueryOptions'
import { queryClient } from '../main'
import type { ErrorComponentProps } from '@benjavicente/solid-router'

export function PostErrorComponent({ error, reset }: ErrorComponentProps) {
  const router = useRouter()
  if (error instanceof PostNotFoundError) {
    return <div>{error.message}</div>
  }

  createEffect(() => {
    reset()
    queryClient.resetQueries()
  })

  return (
    <div>
      <button
        onClick={() => {
          router.invalidate()
        }}
      >
        retry
      </button>
      <ErrorComponent error={error} />
    </div>
  )
}

export const Route = createFileRoute('/posts/$postId')({
  loader: ({ context: { queryClient }, params: { postId } }) => {
    return queryClient.ensureQueryData(postQueryOptions(postId))
  },
  errorComponent: PostErrorComponent,
  component: PostComponent,
})

function PostComponent() {
  const params = Route.useParams()
  const post = createMemo(() =>
    useQuery(() => postQueryOptions(params().postId)),
  )

  return (
    <div class="space-y-2">
      <h4 class="text-xl font-bold underline">{post().data?.title}</h4>
      <div class="text-sm">{post().data?.body}</div>
    </div>
  )
}
