// examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.index.tsx
import { createFileRoute } from '@benjavicente/react-router'
import * as React from 'react'

import { useSuspenseQuery } from '@tanstack/react-query'
import { invoicesQueryOptions } from '../utils/queryOptions'

export const Route = createFileRoute('/dashboard/')({
  loader: (opts) =>
    opts.context.queryClient.ensureQueryData(invoicesQueryOptions()),
  component: DashboardIndexComponent,
})

function DashboardIndexComponent() {
  const invoicesQuery = useSuspenseQuery(invoicesQueryOptions())
  const invoices = invoicesQuery.data

  return (
    <div className="p-2">
      <div className="p-2">
        Welcome to the dashboard! You have{' '}
        <strong>{invoices.length} total invoices</strong>.
      </div>
    </div>
  )
}

// examples/solid/kitchen-sink-file-based/src/routes/dashboard.index.tsx
import { createFileRoute } from '@benjavicente/solid-router'
import * as Solid from 'solid-js'

import { fetchInvoices } from '../utils/mockTodos'

export const Route = createFileRoute('/dashboard/')({
  loader: () => fetchInvoices(),
  component: DashboardIndexComponent,
})

function DashboardIndexComponent() {
  const invoices = Route.useLoaderData()

  return (
    <div class="p-2">
      <div class="p-2">
        Welcome to the dashboard! You have{' '}
        <strong>{invoices.length} total invoices</strong>.
      </div>
    </div>
  )
}
