// examples/react/kitchen-sink-react-query-file-based/src/routes/dashboard.route.tsx
import { createFileRoute } from '@benjavicente/react-router'
import * as React from 'react'
import { Link, Outlet } from '@benjavicente/react-router'

export const Route = createFileRoute('/dashboard')({
  component: DashboardComponent,
})

function DashboardComponent() {
  return (
    <>
      <div className="flex items-center border-b">
        <h2 className="text-xl p-2">Dashboard</h2>
      </div>
      <div className="flex flex-wrap divide-x">
        {(
          [
            ['/dashboard', 'Summary', true],
            ['/dashboard/invoices', 'Invoices'],
            ['/dashboard/users', 'Users'],
          ] as const
        ).map(([to, label, exact]) => {
          return (
            <Link
              key={to}
              to={to}
              activeOptions={{ exact }}
              activeProps={{ className: `font-bold` }}
              className="p-2"
            >
              {label}
            </Link>
          )
        })}
      </div>
      <hr />
      <Outlet />
    </>
  )
}

// examples/solid/kitchen-sink-file-based/src/routes/dashboard.route.tsx
import { createFileRoute } from '@benjavicente/solid-router'
import * as Solid from 'solid-js'
import { Link, Outlet, linkOptions } from '@benjavicente/solid-router'

export const Route = createFileRoute('/dashboard')({
  component: DashboardComponent,
  loader: () => ({
    crumb: 'Dashboard',
  }),
})

const options = [
  linkOptions({
    to: '/dashboard',
    label: 'Summary',
    activeOptions: { exact: true },
  }),
  linkOptions({
    to: '/dashboard/invoices',
    label: 'Invoices',
  }),
  linkOptions({
    to: '/dashboard/users',
    label: 'Users',
  }),
]

function DashboardComponent() {
  return (
    <>
      <div class="flex items-center border-b">
        <h2 class="text-xl p-2">Dashboard</h2>
      </div>

      <div class="flex flex-wrap divide-x">
        {options.map((option) => {
          return (
            <Link {...option} activeProps={{ class: `font-bold` }} class="p-2">
              {option.label}
            </Link>
          )
        })}
      </div>
      <hr />

      <Outlet />
    </>
  )
}
