// examples/react/basic-react-query-file-based/src/routes/__root.tsx
import * as React from 'react'
import {
  Link,
  Outlet,
  createRootRouteWithContext,
} from '@benjavicente/react-router'
import { TanStackRouterDevtools } from '@benjavicente/react-router-devtools'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import type { QueryClient } from '@tanstack/react-query'

export const Route = createRootRouteWithContext<{
  queryClient: QueryClient
}>()({
  component: RootComponent,
  notFoundComponent: () => {
    return (
      <div>
        <p>This is the notFoundComponent configured on root route</p>
        <Link to="/">Start Over</Link>
      </div>
    )
  },
})

function RootComponent() {
  return (
    <>
      <div className="p-2 flex gap-2 text-lg">
        <Link
          to="/"
          activeProps={{
            className: 'font-bold',
          }}
          activeOptions={{ exact: true }}
        >
          Home
        </Link>{' '}
        <Link
          to="/posts"
          activeProps={{
            className: 'font-bold',
          }}
        >
          Posts
        </Link>{' '}
        <Link
          to="/route-a"
          activeProps={{
            className: 'font-bold',
          }}
        >
          Pathless Layout
        </Link>{' '}
        <Link
          // @ts-expect-error
          to="/this-route-does-not-exist"
          activeProps={{
            className: 'font-bold',
          }}
        >
          This Route Does Not Exist
        </Link>
      </div>
      <hr />
      <Outlet />
      <ReactQueryDevtools buttonPosition="top-right" />
      <TanStackRouterDevtools position="bottom-right" />
    </>
  )
}

// examples/vue/basic-file-based-sfc/src/routes/__root.component.vue
<script setup lang="ts">
import {
  Link,
  Outlet,
  HeadContent,
  useRouter,
  useCanGoBack,
  useRouterState,
} from '@benjavicente/vue-router'
import { TanStackRouterDevtools } from '@benjavicente/vue-router-devtools'

const router = useRouter()
const canGoBack = useCanGoBack()
// test useRouterState doesn't crash client side navigation
const _state = useRouterState()
</script>

<template>
  <HeadContent />
  <div class="flex gap-2 p-2 text-lg border-b">
    <button
      data-testid="back-button"
      :disabled="!canGoBack"
      @click="router.history.back()"
      :class="{ 'line-through': !canGoBack }"
    >
      Back
    </button>
    <Link
      to="/"
      :activeProps="{ class: 'font-bold' }"
      :activeOptions="{ exact: true }"
    >
      Home
    </Link>
    <Link to="/posts" :activeProps="{ class: 'font-bold' }">Posts</Link>
    <Link to="/layout-a" :activeProps="{ class: 'font-bold' }">Layout</Link>
    <Link
      to="/onlyrouteinside"
      data-testid="link-to-only-route-inside-group"
      :search="{ hello: 'world' }"
      :activeProps="{ class: 'font-bold' }"
    >
      Only Route Inside Group
    </Link>
    <Link
      to="/inside"
      data-testid="link-to-route-inside-group"
      :search="{ hello: 'world' }"
      :activeProps="{ class: 'font-bold' }"
    >
      Inside Group
    </Link>
    <Link
      to="/subfolder/inside"
      data-testid="link-to-route-inside-group-inside-subfolder"
      :search="{ hello: 'world' }"
      :activeProps="{ class: 'font-bold' }"
    >
      Inside Subfolder Inside Group
    </Link>
    <Link
      to="/insidelayout"
      data-testid="link-to-route-inside-group-inside-layout"
      :search="{ hello: 'world' }"
      :activeProps="{ class: 'font-bold' }"
    >
      Inside Group Inside Layout
    </Link>
    <Link
      to="/lazyinside"
      data-testid="link-to-lazy-route-inside-group"
      :search="{ hello: 'world' }"
      :activeProps="{ class: 'font-bold' }"
    >
      Lazy Inside Group
    </Link>
    <Link to="/대한민국" :activeProps="{ class: 'font-bold' }"
      >unicode path</Link
    >
    <Link
      :activeProps="{ class: 'font-bold' }"
      :to="'/this-route-does-not-exist' as any"
    >
      This Route Does Not Exist
    </Link>
  </div>
  <hr />
  <Outlet />
  <TanStackRouterDevtools position="bottom-right" />
</template>
