// examples/react/basic-file-based/src/routes/posts.$postId.tsx
import { createFileRoute } from '@benjavicente/react-router'
import * as React from 'react'
import { ErrorComponent } from '@benjavicente/react-router'
import { fetchPost } from '../posts'
import type { ErrorComponentProps } from '@benjavicente/react-router'

export const Route = createFileRoute('/posts/$postId')({
  loader: async ({ params: { postId } }) => fetchPost(postId),
  errorComponent: PostErrorComponent,
  notFoundComponent: () => {
    return <p>Post not found</p>
  },
  component: PostComponent,
})

export function PostErrorComponent({ error }: ErrorComponentProps) {
  return <ErrorComponent error={error} />
}

function PostComponent() {
  const post = Route.useLoaderData()

  return (
    <div className="space-y-2">
      <h4 className="text-xl font-bold underline">{post.title}</h4>
      <div className="text-sm">{post.body}</div>
    </div>
  )
}

// examples/vue/basic-file-based-sfc/src/routes/posts.$postId.component.vue
<script setup lang="ts">
import { useLoaderData } from '@benjavicente/vue-router'
import type { PostType } from '../posts'

const post = useLoaderData({ from: '/posts/$postId' }) as unknown as PostType
</script>

<template>
  <div class="space-y-2">
    <h4 class="text-xl font-bold underline" data-testid="post-title">
      {{ post.title }}
    </h4>
    <div class="text-sm">{{ post.body }}</div>
  </div>
</template>
