// packages/solid-router/src/awaited.tsx
import * as Solid from 'solid-js'

import { TSR_DEFERRED_PROMISE, defer } from '@benjavicente/router-core'
import type { DeferredPromise } from '@benjavicente/router-core'
import type { SolidNode } from './route'

export type AwaitOptions<T> = {
  promise: Promise<T>
}

export function useAwaited<T>({
  promise: _promise,
}: AwaitOptions<T>): [T, DeferredPromise<T>] {
  const promise = defer(_promise)

  if (promise[TSR_DEFERRED_PROMISE].status === 'pending') {
    throw promise
  }

  if (promise[TSR_DEFERRED_PROMISE].status === 'error') {
    throw promise[TSR_DEFERRED_PROMISE].error
  }

  return [promise[TSR_DEFERRED_PROMISE].data, promise]
}

export function Await<T>(
  props: AwaitOptions<T> & {
    fallback?: SolidNode
    children: (result: T) => SolidNode
  },
) {
  if (!('fallback' in props)) {
    const [resource] = Solid.createResource(
      () => defer(props.promise),
      (p) => p,
      {
        deferStream: true,
      },
    )

    return (
      <Solid.Show when={resource()}>
        {(data) => props.children(data())}
      </Solid.Show>
    )
  }

  return (
    <Solid.Suspense fallback={props.fallback}>
      <AwaitInner {...props} />
    </Solid.Suspense>
  )
}

function AwaitInner<T>(
  props: AwaitOptions<T> & {
    fallback?: SolidNode
    children: (result: T) => SolidNode
  },
) {
  const [resource] = Solid.createResource(
    () => defer(props.promise),
    (p) => p,
  )

  return props.children(resource() as T)
}

// packages/react-router/src/awaited.tsx
import * as React from 'react'

import { TSR_DEFERRED_PROMISE, defer } from '@benjavicente/router-core'
import { reactUse } from './utils'

export type AwaitOptions<T> = {
  promise: Promise<T>
}

/** Suspend until a deferred promise resolves or rejects and return its data. */
export function useAwaited<T>({ promise: _promise }: AwaitOptions<T>): T {
  if (reactUse) {
    const data = reactUse(_promise)
    return data
  }
  const promise = defer(_promise)

  if (promise[TSR_DEFERRED_PROMISE].status === 'pending') {
    throw promise
  }

  if (promise[TSR_DEFERRED_PROMISE].status === 'error') {
    throw promise[TSR_DEFERRED_PROMISE].error
  }

  return promise[TSR_DEFERRED_PROMISE].data
}

/**
 * Component that suspends on a deferred promise and renders its child with
 * the resolved value. Optionally provides a Suspense fallback.
 */
export function Await<T>(
  props: AwaitOptions<T> & {
    fallback?: React.ReactNode
    children: (result: T) => React.ReactNode
  },
) {
  const inner = <AwaitInner {...props} />
  if (props.fallback) {
    return <React.Suspense fallback={props.fallback}>{inner}</React.Suspense>
  }
  return inner
}

function AwaitInner<T>(
  props: AwaitOptions<T> & {
    fallback?: React.ReactNode
    children: (result: T) => React.ReactNode
  },
): React.JSX.Element {
  const data = useAwaited(props)

  return props.children(data) as React.JSX.Element
}
